#!/usr/bin/env bash

{ # this ensures the entire script is downloaded #

set -o errtrace
set -o errexit

COLOR_GREEN="\033[32m"
COLOR_BLUE="\033[34m"
COLOR_DARK_GRAY="\033[38m"
COLOR_NORMAL="\033[39m"

GITHUB_URL="https://api.github.com/repos/bromanko/dot-slash-go/releases/latest"
RELEASE_VERSION=`curl --silent ${GITHUB_URL} \
  | grep '"tag_name":' \
  | sed -E 's/.*"([^"]+)".*/\1/'`
RELEASE_URL=`curl --silent ${GITHUB_URL} \
  | grep '"browser_download_url":' \
  | sed -E 's/.*"([^"]+)".*/\1/'`

echo -e "${COLOR_BLUE}Installing dot-slash-go ${RELEASE_VERSION}${COLOR_NORMAL}"
echo -e "${COLOR_DARK_GRAY}${RELEASE_URL}${COLOR_NORMAL}"

curl -sL ${RELEASE_URL} | tar xz



echo -e "\n"
echo -e "Great! You're all set."
echo -e "Check things out by running ${COLOR_GREEN}./go${COLOR_NORMAL}"

} # this ensures the entire script is downloaded #
